<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://localhost/HelloWorld/"     
        xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="HelloWorld"   
        targetNamespace="http://localhost/HelloWorld/">
  <wsdl:message name="sayHelloRequest">
    <wsdl:part name="yourName" type="xsd:string"/>
  </wsdl:message>
  <wsdl:message name="sayHelloResponse">
    <wsdl:part name="greeting" type="xsd:string"/>
  </wsdl:message>
  <wsdl:portType name="HelloWorld">
    <wsdl:operation name="sayHello">
      <wsdl:input message="tns:sayHelloRequest"/>
      <wsdl:output message="tns:sayHelloResponse"/>
    </wsdl:operation>
  </wsdl:portType>
   <wsdl:binding name="HelloWorldSOAP" type="tns:HelloWorld">
     <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="sayHello">
          <soap:operation soapAction="cc:HelloWorldService:HelloWorld#sayHello"/>
           <wsdl:input>
             <soap:body namespace="http://localhost/HelloWorld/" use="literal"/>
           </wsdl:input>
           <wsdl:output>
             <soap:body namespace="http://localhost/HelloWorld/" use="literal"/>
           </wsdl:output>
        </wsdl:operation>
   </wsdl:binding>
  <wsdl:service name="HelloWorld">
    <wsdl:port binding="tns:HelloWorldSOAP" name="HelloWorldSOAP">
      <soap:address location="http://localhost:8080/ccx/HelloWorld"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
